### ISSUE TITLE
Support current version of nesting

### ISSUE THREAD

**Issue by vrugtehagel** [ryboe/CSS3#185]
The CSS3 package supports the older draft specification for nesting, i.e. `@nest` and selectors starting with `&`.

The current specification (and what browsers have implemented) supports nesting without either of these;
```css
.foo {
  custom-element {
    color: red;
  }
}
```
should highlight correctly, as above.
