### ISSUE TITLE
Support `repeat()` inside `grid-template`

### ISSUE THREAD

**Issue by vrugtehagel** [ryboe/CSS3#194]
Declarations such as
```css
* {
    grid-template: auto / repeat(3, 1fr);
}
```
are perfectly valid CSS, but the CSS3 package doesn't recognize the `repeat()` function in this context.

<img width="356" alt="image" src="https://github.com/ryboe/CSS3/assets/41021050/2ac8c823-427a-43c9-a9f2-d12104e6c6c6">

It is recognized in `grid-template-rows` and `grid-template-columns`, however.
