### ISSUE TITLE
Add view transition support

### ISSUE THREAD

**Issue by argyleink** [ryboe/CSS3#199]
https://developer.chrome.com/docs/web-platform/view-transitions/

```css
::view-transition,
::view-transition-group(),
::view-transition-image-pair(),
::view-transition-old(),
::view-transition-new() {
  view-transition-name: somename;
}
```
