### ISSUE TITLE
Bug: highlighting breaks under nested container queries

### ISSUE THREAD

**Issue by ryami333** [ryboe/CSS3#202]
The following CSS breaks syntax highlighting:

```css
.container {
  display: none;

  @container (min-width: 400px) {
    display: block;
  }
}
```

Preview:

<img width="308" alt="Screenshot 2024-03-06 at 18 05 51" src="https://github.com/ryboe/CSS3/assets/12481532/2a5c4f16-0092-4677-89e5-e11e2fa2570c">
